<?php
$ADMI2014 = array(
"2014 College Admission", "Congratulations to Class of 2014 College Admission", 
"Harvard", "Priyanka & Harrison (early)", 
"Yale", "George", 
"Princeton", "Reva & Noshin", 
"Columbia", "Kaveh, Ashley, George", 
"Brown", "Diane(early) & Eric", 
"U-penn", "Meghana, Sharon, Natalie", 
"MIT", "George", 
"Dartmouth", "Oliver", 
"U.Chicago", "Adam, Ben, Reva, Kaveh, Noshin", 
"Duke", "Ashley, Amanda, Estee, Noshin", 
"Johns Hopkins", "Chris, Eklavya, Vincent, Paul, Sharon, Jeffrey, Noshin", 
"Cornell", "Daniel, Nick, Kelly, Amanda, Ashley, George, Reva, Siddesh, Noshin, Richard, Katrina", 
"NYU Stern", "Rachel, Matt(early)", 
"Georgetown", "Sharon", 
"Cooper Union", "Jonathan", 
"Cal tech", "Noshin", 
"Carnegie Melon", "Christine, Joann, Jeffrey", 
"Berkley", "Deepika, Joseph, Paul", 
);
?>