<?php
$ADMI2013 = array(
"2013 College Admission", "Congratulations to the Class of 2013 College Admission", 
"Harvard", "Julie & Michelle (early), Nakul ", 
"Yale", "Nakul ", 
"Princeton", "Jade (early), Amilia", 
"MIT", "Lambert & Raymond (early) ", 
"Columbia", "Anhinaba & Sachi (early), Puja", 
"U-Penn", "David (Wharton early)", 
"Caltech", "Daniel", 
"Berkley", "Brendon, Michael ", 
"Duke", "Ben (Early), Brendan", 
"Chicago", "Selena, Rohan & Daniel (Early), Puja", 
"Hopkins", "Daniel, Richard, Judy", 
"Cornell", "Emily & Susan (Early), Sonya, Tanya", 
);
?>