<?php

$ADMI2012 = array(
"2012 College Admission", "CONGRATULATIONS to class of 2012 College Admission", 
"Harvard", 			"Raymond  (early)", 
"Yale", 			"Kristine", 
"Oxford", 			"Billy", 
"Princeton", 		"Angad (early),  Brian,  Maha", 
"Columbia", 		"Kimberly (early),  Kristine, Tom", 
"U Penn", 			"Maha,  Matty", 
"Brown", 			"Diana", 
"Dartmouth", 		"Anjeli,  Christine, Robert", 
"Duke",				"Andrew,  Angeli, April, Tom, Robert",
"Chicago",		"Roberta",
"Hopkins",	"Maha,  Roberta",
"Cornell", 			"Heemee (early),  Jessica (early), April,  David,  Lily", 
);

?>