<?php
$ADMISSIONLIST = array(
"09-11 College Admission", "CONGRATULATIONS to class 2009 - 2011 College Admission", 
"Harvard", "Esther(09), Kevin(09)", 
"Yale", "Sherif(09), Nicolas(09), Jane(09)", 
"Princeton", "Quan(11), Deana(11), Nizar(09), Payam(09), Kevin(09)", 
"Columbia", "Daniel(11), Amanda(11), Michael(11), Kevin(11), Quan(11), Brian(10), <br>					Sonia (10), Dhriste(09), Jane(09)", 
"U Penn", "Monica(11), Quan(11), Nikita(10), Sonia(10), Wonah(10), Michelle(09), Trisha(09), Kim(09)", 
"U Penn Wharton", "Kevin(11), Andrew(09), Andy(09), Steven(09)", 
"Brown", "Jane(09),  Christopher(10)", 
"Brown Medical", "Timothy(11), Matthew(11), Sarita(09)", 
"Dartmouth", "Emanuel(11), Cathy(09), Daniel(09), Kim(09), Lipsa(10), Patty(09), <br>					Sam(09), Sonia(10), Steven(09), Yesha(10)", 
"Cornell", "Sean(11), Rahim(11), Janson(11), David(11), Felice(11), Kevin(11), <br>					Pam(11), James(11), Bella(11), Quan(11), Joseph(11), Helena(11), <br>					Tanuji(11), Alex(09), Andrew(10), Andy(09), Belle(09), Cathy(09), <br>					Daniel(09), Diana(10), Edward(09), Eric(09), Heena(09), Jason(10), Patty(09),					Peter(09), Sachin(10), Shelly(10), Sonia(10), Wonah(10)", 
"Cal Tech", "Quan(11)", 
"MIT", "Esther(09)", 
"Stanford", "David(09)", 
);
?>