<?php
$PSATHIGHSCORE = array(
"2010 PSAT High Score", "2010 PSAT High Score Achievers", 
"230-240", "Billy, Angeli, Raymond & Kimberly ...", 
"220-230", "Ashwin, Tom, Melissa, Sean & Agand ...", 
);

$SATIHIGHSCORE = array(
"2012 High SAT I Score", "Congratulations to High SAT I Score Achievers", 
"2400", "Max Lee (Mar. 2012), Sachi Patil (Mar. 2012)", 
"2390", "Tom W. (Mar. 2011)",
"2380", "Raymond W. (Nov. 2011)",
"2300+", "Ashwin K.,  Amilia X.,  Brian S., Anjeli S.,  Raymond K,  Sean P. Billy S.,  Angad A. (Jan. 11 - Mar. 12)"
);
?>