<?php
include_once("admission/admi2017_8.inc");
include_once("admission/admi2017_7.inc");
include_once("admission/admi2016_6.inc");
include_once("admission/admi2014_5.inc");
include_once("admission/admi2014.inc");
include_once("admission/admi2013.inc");
include_once("admission/admi2012.inc");
include_once("admission/admissionlist.inc");
include_once("admission/cong2014.inc");
include_once("admission/psatscore.inc");















$ADMISSION_VAR = array($ADMI2017_8, $ADMI2017_7, $ADMI2016_6, $ADMI2014_5, $CONG2014, $ADMI2014, $ADMI2013, $ADMI2012, $ADMISSIONLIST, );

$ADMISSION_VAR_NAME = array("ADMI2017_8", "ADMI2017_7", "ADMI2016_6", "ADMI2014_5", "CONG2014", "ADMI2014", "ADMI2013", "ADMI2012", "ADMISSIONLIST", );

?>
