<?php
$ADMI2017_8 = array(
"2017 College Admission", "2017 College Admission", 
"Harvard", "Ben (Early), Jackie, Justin, Mohamed & Sam", 
"Yale", "Jackie, Justin", 
"Princeton", "Jackie, Max (Early)", 
"Stanford", "Sejar", 
"UPenn", "Anjeli (Early), Sejar", 
"Columbia", "Jackie, Shiv (Early)", 
"Northwestern (Medical)", "Eugene (HPME)", 
"Brown", "Alex (Early), Justin (PLME), Mohamed", 
"Duke", "Chris 1, Jeffrey (Early)", 
"UChicago", "Rushabh", 
"Johns Hopkins", "Caleb, Lydia (Early), Seunghyun, Shane (Early)", 
"Georgetown", "Grace, Sejar, Seunghyun", 
"Cornell", "Amy (Early), Chris 1, Chris 2, Ethan, Eugene, Grace, Jeremy, Kevin, Mohamed, Yoonjin", 
);
?>