<?php

$CLASS_NAME = array(
		"PS-B", "4",
		"PS-A", "5",
		"IS-C", "6",
		"IS-A", "7",
		"HS-D Eng", "8",
		"HS-D1", "8",
		"HS-D2", "8",
		"HS-C1", "9",
		"HS-C2", "10",
		"HS-B", "12",
		"TUTO", "12"
);


$STUDENT_VAR = array(
		"#studentname",
		"#studentlogin",
		"#studentid",
		"#studentemail",
		"#studentpassword"
);

$STUDENT_VAR1 = array( "#name#", "#login#", "#id#", "#email#", "#password#");

?>

