<?php

$SCHEDULELISTR = array(
"2017 Spring Saturday Class", 1, 
array("01/21/2017", " 9:30am-12:30pm", " Session 1 "),
array("01/28/2017", " 9:30am-12:30pm", " Session 2"),
array("02/04/2017", " 9:30am-12:30pm", " Session 3"),
array("02/11/2017", " 9:30am-12:30pm", " Session 4 "),
array("02/25/2017", " 9:30am-12:30pm", " Session 5"),
array("03/04/2017", " 8:30am-12:30pm", " Session 6  (Test #1)"),
array("03/11/2017", " 9:30am-12:30pm", " Session 7"),
array("03/18/2017", " 9:30am-12:30pm", " Session 8 "),
array("03/25/2017", " 9:30am-12:30pm", " Session 9"),
array("04/01/2017", " 9:30am-12:30pm", " Session 10"),
array("04/08/2017", " 9:30am-12:30pm", " Session 11 "),
array("04/22/2017", " 8:30am-12:30pm", " Session 12 (Test #2)"),
array("04/29/2017", " 9:30am-12:30pm", " Session 13"),
array("05/06/2017", " 9:30am-12:30pm", " Session 14"),
array("05/13/2017", " 9:30am-12:30pm", " Session 15"),
array("05/20/2017", " 9:30am-12:30pm", " Session 16"),
array("05/27/2017", " 9:30am-12:30pm", " Session 17"),
array("06/03/2017", " 8:30am-12:30pm", " Session 18 (Final Exams)"),
array(" ", " ")
);

$TESTTAKERLISTR = array(
"TestTakers' SAT", 0,
array("08/18/2014", "6pm-10pm", "Orientation", "Take Diagnostic SAT #11"),
array("08/20/2014", "", "M : TestTaking Techniques", "R/W : Sentence Completions"),
array("08/25/2014", "", "M : Arithmetic/Algebra", "R/W : Error ID"),
array("08/27/2014", "", "M : TT Techniques Review", "R/W : Reading Passages #1"),
array("09/03/2014", "", "M : Arith/Algebra Review", "R/W : Sentence Improvement"),
array("09/04/2014", "6pm-10pm", "Take Diagnostic SAT #2"),
array("09/08/2014", "", "M : Geometry", "R/W : Reading Passages #2"),
array("09/10/2014", "", "M : Review Diagnostic SAT #2", "R/W : Review Diagnostic SAT #2"),
array("09/15/2014", "", "M : Functions and Graphs", "R/W : Essay/Paragraph Improve"),
array("09/17/2014", "6pm-10pm", "Take Diagnostic SAT #3"),
array("09/22/2014", "", "M : Geometry Review", "R/W : Reading Comp Review"),
array("09/24/2014", "", "M : Review Diagnostic SAT #3", "R/W : Review Diagnostic SAT #3"),
array("09/29/2014", "", "M : TTT Review #2", "R/W : Complete Writing Review"),
array("10/01/2014", "6pm-8:30pm", "Take Diagnostic SAT #4"),
array("10/06/2014", "", "M : Review Diagnostic SAT #4", "R/W : Review Diagnostic SAT #4"),
array("10/08/2014", "", "M : Complete Math Review", "R/W : Complete Reading Review"),
array("10/13/2014", "", "M : Practice PSAT & Review", "R/W : Practice PSAT & Review"),
array("10/15/2014", "", " NO CLASS! ")
);


?>

