<?php 

//$SCHEDULE_MENU = array( "AP & SAT II", "Regents", "ACT & SAT I", "NYS Test", "Summer School");
//$SCHEDULE_MENU = array("Fall Semester", "SAT I", "PSAT", "Summer School");
//$SCHEDULE_MENU = array("Summer School",  "AP/SAT II", "ACT", "Regents", "NYS ELA & Math Test");
//$SCHEDULE_MENU = array("TestTakers SAT/PSAT",  "CTY", "PSAT", "Fall Saturday School");
//$SCHEDULE_MENU = array("Spring Semester", "Jan. SAT Prep.", "CTY SAT & SCAT Prep.", "March SAT Prep.",  "Fall Saturday School");

$M_SUMMER = 0;
$M_SPRING = 5;
$M_FALL = 6;
$M_APSAATII = 1;
$M_ACT = 2;
$M_NYSELA = 3;
$M_REGENTS = 4;
$M_TAKERS = 7;
$M_SAT = 8;
$M_CTY = 9;
$M_PSAT = 10;
$M_AP11 = 11;
$M_SAT12 = 12;
$M_REGENTS11 = 11;
$M_SAT12 = 12;
$M_SAT13 = 13;
$M_SAT14 = 14;
include_once(includes_path()."/schedule_menu_include.inc");


?>