<?php

$S_INDEX_MENU = array(
	array("Summer School", 1,	$M_SUMMER, "M_SUMMER", array("2016 Summer School", "SU17Brochure-2.doc", "SU2017.JPG")),
	array("Regents ", 1,	$M_REGENTS11, "M_REGENTS11", array("Regents Review Course", "2017Regents Revised.doc", "2017 Regents.JPG")),
	array("AP & SAT II History", 1,	$M_REGENTS, "M_REGENTS", array("", "2017AP_SAT2-History.doc", "AP&SAT II History Revised- 2017.JPG")),
	array("AP & SAT II Science", 1,	$M_APSAATII, "M_APSAATII", array("", "2017AP&SAT2-Science.doc", "AP&SAT II Science - 2017.JPG")),
	array("SAT II Math & Science", 1,	$M_SAT12, "M_SAT12", array("", "2017SAT2-ScienceSchedule.doc", "SAT II Science & Math - 2017.JPG")),
	array("ACT", 1,	$M_ACT, "M_ACT", array("ACT Course for April 2017 Test", "2017 April ACT - Revised.docx", "ACT for 2017 April Revised.JPG")),
	array("SAT I", 1,	$M_SAT, "M_SAT", array(" ", "TT2016FALL.docx", "TT2016.PNG")),
	array("TestTakers SAT/PSAT", 0,	$M_TAKERS, "M_TAKERS", array("TestTakers SAT Course for March 2017 Test", "SAT MAR-17.pdf", "Testtakers March 2017.JPG")),
	array("Spring Semester", 0,	$M_SPRING, "M_SPRING", array("LIA Spring 2017 Semester", "sp17bro.pdf", "spring217.PNG")),
	array("SAT I for Jan Test 2017", 0,	$M_SAT13, "M_SAT13", array("SAT I Course for January 2017 Test", "SAT JAN-17.pdf", "SAT Jan 2017.JPG")),
	array("CTY SAT & SCAT Prep.", 0,	$M_CTY, "M_CTY", array("CTY SCAT 2016-2017", "SCAT 16-17.pdf", "CTY 2016 2017.JPG")),
	array("Fall Semester", 0,	$M_FALL, "M_FALL", array("", "FA2016.doc", "FA2016.JPG")),
	array("PSAT", 0,	$M_PSAT, "M_PSAT", array("", "2016PSAT-web.docx", "2016PSAT.PNG")),
	array("NYS ELA / MATH Test", 0,	$M_NYSELA, "M_NYSELA", array("ELA & Math Test Prep. Course", "2015ELA&Math.pdf", "2015ELA&Math.jpg")),
	array("SAT I for Mar Test 2017", 0,	$M_SAT14, "M_SAT14")
);
?>
