<?php
$_SUMMERTOP = array(
"Grade 4 :", " ",
"Rabiya Rahaman", "155",
"Riya Ramki", "129",
"Grade 5 :", " ",
"Harmehar Kaur", "173",
"Aaron Jacob", "173",
"Anjali Tooley", "165",
"Fayyad Chowdhury", "164",
" ", " ",

"Grade 6 :", " ",
"Jaysukh Singh", "172",
"Ashley Wong", "164",
"Raymond Li", "140",
" ", " ",

"Grade 7 :", " ",
"Arya Tooley", "184",
"Rishi Aravied", "178",
"Niyanth Ponnusamyy", "172",
" ", " ",

"Grade 8 :", " ",
"Sophia Gu", "177",
"Naann Shao", "177",
"Savannah Ma", "171",
"Dharmik Namineni", "163",
" ", " ",

"Grade 9 :", " ",
"Sebastian Ng", "157",
"Samuel Park", "157",
"Maggie Yu", "153",
"Cody Chen", "145",
" ", " ",

"Grade 10 :", " ",
"Fatema Rahman", "167",
"Nicholas Han", "163",
"Kaityln Li", "151",
" ", " ",

"Grade 11-12 :", " ",
"Doreen Dong", "163",
"Jennifer Zhu", "151",
"Ansh Jhaveri", "141",
" ", " ",

);

?>
